korean_manhwas = {
    "Greatest Outcast", "Terror man", "Solo leveling", "Revival man", "Appetite",
    "The lady and her Butler", "My secret brother", "Flow", "Epic of Gilgamesh",
    "Tales of eun aran", "Let's play (Mongie)", "unOrdinary", "Que Sera Sera",
    "Life Howling", "White Epic", "A Fairytale for the Demon Lord", "Blade Note",
    "Ultimate Legend - Kang Hae Hyo", "Broken Melody", "Doridosim",
    "unTouchable", "Our Relationship Is...", "Forever Mine", "Premarital Relationship",
    "The Fiancées Live Together", "Unbalance x3", "Hero Waltz", "Sweet X Trouble",
    "The Legendary Moonlight Sculptor", "Skeleton Soldier Couldn't Protect the Dungeon",
    "Wind Breaker", "Real Account", "Please Take My Brother Away!", "A Returner's Magic Should Be Special",
    "Distant Sky", "Mode II", "Lovely Bokhee-ssi", "Dokgo Rewind",
    "Dokgo", "Dokgo2", "Free Draw", "My Naughty Sweetheart", "Pride Complex",
    "Into the Net!", "Skill of Lure", "Oh! Holy", "Song of the Cloud",
    "His Barcode Tattoo", "We're so Over.. or Not", "Special Martial Arts Extreme Hell Private High School",
    "City of the Dead Sorcerer", "MZ", "I Am The Sorcerer King", "The World Where I Belong",
    "The Road of Karma", "Boss in School", "The Girl from Random Chatting", "Her Summon",
    "Warble", "Springtime for Blossom", "Annoying Alice", "Mr.Kang", "The V Squad",
    "Legend: The Beginning", "School Shock", "Sweetheart : The Boss Is Too Kind!",
    "My Dear Vampire Lord", "The Superb Captain in the City", "Battle Frenzy",
    "The Strongest War God", "Vicious Luck", "The Beginning After The End",
    "Mercenary Enrollment", "Tomb Raider King", "Return Survival", "Max Level Returner",
    "Memorize", "Gang of School", "Jungle Juice", "Reverse Villain", "Reincarnation Cycle",
    "Strongest Worker", "Study Group", "Promised Orchid", "The Strongest Ever", "The God of Death",
    "The Great Mage Returns After 4000years", "Path of the Shaman", "My Dad Is Too Strong",
    "Second Life of a Gangster", "FFF-class Trash Hero", "List of Villains", "The Thorn That Pierces Me",
    "Gangam Dokkaebi", "The Tutorial Tower's Advanced Player", "Worn and Torn Newbie",
    "The Constellation That Returned From Hell", "Spirit Farmer", "Kill the Hero",
    "Incompetent Villain", "How to fight", "The Dungeon Master", "Survival Story Of A Sword King In A Fantasy World",
    "My Husband Hides His Beauty", "Omniscient Reader’s Viewpoint", "Greatest Boss System",
    "I Have An Apocalyptic Dungeon", "It All Starts With Playing Game Seriously", "I was Stuck on the Same Day for One Hundred Thousand Years",
    "The All-Devouring Whale", "Psycho Revenge", "Return of the 8th Class Magician", "Back To Rule Again",
    "It Starts with a kingpin account", "The Heavenly Demon Can’t Live a Normal Life", "The Return of the Crazy Demon",
    "The Lord of Money", "Post-apocalyptic Dispatch Company", "Return of The Bachelor",
    "The Max Level Hero has Returned!", "Story of thorny spear", "The Book of Lagier", "Taming Master",
    "Nano Machine", "The Descent of the Demonic Master", "I'm Destined for Greatness!", "Slave B",
    "Player Who Can't Level Up", "A Bad Person", "The Boy of Death", "Sss-class Suicide Hunter",
    "True Education", "From the Grave and Back", "God of Blackfield", "The Book Eating Magician",
    "Trapped in a Webnovel as a Good-For-Nothing", "Return of the Disaster class hero", "Manager Kim",
    "Boxer", "Real Man", "I Reincarnated As The Crazed Heir", "+99 Wooden Stick", "Doom breaker",
    "I Obtained a Mythic Item", "Star Instructor, Master Baek", "The Knight King Who Returned with a God",
    "The Priest of Corruption", "Chronicles of the Demon Faction", "Amentia"
}

chinese_manhuas = {
    "Moshi fanren", "Spirit sword sovereign", "Eternal reverence", "Red spirit",
    "Renegade immortal", "Don's Adventure in Another World", "Divine Throne",
    "Holy Ancestor", "Martial Legacy", "My Boyfriend is Jinyiwei", "I was trash",
    "So Pure, So Flirtatious", "Chang an demon song", "Martial God's space", "Mayabi",
    "The Demon Leader Quickly Lie Down", "Iron Ladies", "The Boy in the All-Girls School",
    "Treading on Fire, Yuwen Jun!", "My Great Sword", "I Am a Great God",
    "Ten Thousand Paths to Becoming a God", "Apotheosis", "My Wife is a Demon Queen",
    "Metropolitan System", "Relase That Witch", "Tian Jiang Xian Shu Nan", "Chunqing Yatou Huolala",
    "Demonic Housekeeper", "Bringing the Nation's Husband Home", "Adonis Next Door",
    "Zhi Ran Chenghun", "Best Wedding", "Teach the Devil Husband", "Arrogant CEO: Wife Hunter",
    "Lang Huan Library", "Master of Legendary Realms", "Skill Unparalleled", "Mo,don't run!",
    "Professor President,Come On", "Two-Faced Teacher's Night Class", "My Apprentice is A Pig",
    "My Apprentice: Game over Again!", "Sweetheart : The Boss Is Too Kind!", "My Dear Vampire Lord",
    "The Superb Captain in the City", "I Have a Mansion in the Post-apocalyptic World",
    "The Sexy Master is Not an Idiot!", "My Maid is a Demon", "My Girlfriend is a Zombie",
    "King Of Apocalypse", "Almighty Master", "Temple of the Dragon King", "Divine Heros Skyfall System",
    "The Strongest God King", "Rebirth of the Eternal Cultivator", "Immortal Swordsman in the Reverse World",
    "Forced to Become the Villain’s Son-in-law", "Magician From The Future", "Immortal Nanny Dad",
    "My Girlfriend is a Villain", "Immortal Demon Dad", "Daddy from Hell", "Ascension To Godhood By Slaying Demons",
    "Carrying The Goddess Along", "I have Nine Female Disciples", "Spicy female Boss",
    "The Rebirth Of The Demon God", "Meng Shi Zai Cang", "I'm an Evil God", "King Killer Reborn",
    "The Queen Is Mighty", "The Demon King Who Lost His Job", "My Wife Is Actually the Empress?",
    "School Flower Master", "Yuanlong", "Infinite Apostles And Twelve War Girls", "My Disciples are Super Gods",
    "Rise of the Demon King", "Immortal Reverence Dad", "I Won’t Get Bullied By Girls", "My Wife is a Fox Spirit",
    "Goddess's Personal Doctor", "Female Cultivators are After Me", "The Strongest Golden Kidney System",
    "Starting From Today I'll Work As A City Lord", "Devil Sword King", "Ultimate Abandoned",
    "Life Of A War Emperor After Retirement", "The Immortal Emperor", "Son-In-Law Above Them All",
    "Does Your Mother Need Son In Law", "My 7Wives Are Forcing Me To Die", "picking up a shool beauty to be wife",
    "The Super Doctor From2089", "I, The Strongest Demon, Have Regained My Youth?!",
    "I Picked Up An Attribute", "Dr.Don", "Metropolitan Reverence", "Please, Don't Livestream It!",
    "Trample on the River of Immortality", "Rules for Peddling in Another World",
    "I am the Strongest Lord in Another World", "Sword God’s Life Is Not That Boring",
    "99Ways to Become Heroes by Beauty Masters", "Cultivator Against Hero Society",
    "All Hail the Sect Leader", "The Special Agent With Negative EQ Reincarnated As A Student And Became Popular With The Ladies?!",
    "My Girlfriend is Long Aotian", "The Great Devil Emperor Development System", "The Great Deity", "It Starts with a Mountain",
    "Legend of the Tyrant Empress", "Keep a Low Profile, Sect Leader", "The first Son-In-Law Vanguard of All Time",
    "Become Villain in the Game Cultivation", "The First Ancestor in History",
    "History of Three States", "My Three Thousand Years To The Sky", "I'm Really Not the Demon God's Lackey",
    "I Became a System", "My Apprentices are All Female Devils", "One Step Toward Freedom", "Strongest Abandoned Son",
    "Rebirth of the Top Villain", "I am Supreme Son in Law", "I am Han Sanqian", "Dao Yin", "World's Apocalypse Online",
    "Return of Immortal Emperor", "Library of Heaven's Path", "The Strong Man from the Mental Hospital",
    "Another Emperor Reborn", "Swallowed Star", "Journey to Heaven", "Invicible at the start",
    "I am Cultivation Bigshot", "Am I Invicible", "I Built a Lifespan Club", "The OutCast"
}